# Generated by Django 6.0.3 on 2026-03-07 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appnotification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='appnotification',
            name='data_payload',
        ),
        migrations.RemoveField(
            model_name='appnotification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='appnotification',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='notification_type',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='is_from_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
