name: food_save
description: "FoodSave — мобильное приложение для снижения пищевых отходов"
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^11.1.0
  animated_text_kit: ^4.3.0
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  gap: ^3.0.1
  dio: ^5.9.2
  path_provider: ^2.1.5
  lottie: ^3.3.2
  shared_preferences: ^2.5.4
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^3.0.3
  image_picker: ^1.2.1
  path: ^1.9.1
  intl: ^0.20.2
  camera: ^0.11.1
  permission_handler: ^11.4.0
  flutter_local_notifications: ^19.0.0
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  auto_route_generator: ^10.5.0
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animations/
    - assets/illustrations/
