# Generated by Django 6.0.3 on 2026-03-07 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Dairy, Meat, Vegetables)', max_length=100)),
                ('icon_name', models.CharField(blank=True, help_text='Flutter IconData name or asset path', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product (e.g., Milk, Tomatoes)', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit', models.CharField(choices=[('PCS', 'шт'), ('G', 'г'), ('KG', 'кг'), ('ML', 'мл'), ('L', 'л')], default='PCS', max_length=10)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(help_text='Best before or use by date')),
                ('status', models.CharField(choices=[('ACTIVE', 'В холодильнике'), ('CONSUMED', 'Съедено'), ('WASTED', 'Выброшено')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional remarks on this product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='fridge.category')),
            ],
            options={
                'ordering': ['expiration_date'],
            },
        ),
    ]
