# Generated by Django 6.0.3 on 2026-03-07 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Recipe Title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short overview of the dish')),
                ('image_url', models.URLField(blank=True, help_text='Link to dish image', max_length=500, null=True)),
                ('prep_time_minutes', models.PositiveIntegerField(default=15, help_text='Preparation time')),
                ('cook_time_minutes', models.PositiveIntegerField(default=30, help_text='Cooking time')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Calories per serving', null=True)),
                ('dietary_tags', models.TextField(blank=True, help_text='Comma-separated tags (e.g., Vegan, Gluten-Free, Keto)')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingredient name (e.g., Apple, Chicken Breast)', max_length=150)),
                ('amount', models.CharField(help_text='Quantity (e.g., 500g, 2 pieces, 1 cup)', max_length=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Order of execution')),
                ('instruction', models.TextField(help_text='What to do in this step')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
